### ISSUE TITLE
Enhancement TODO list

### ISSUE THREAD

**Issue by ManuelLoaizaVasquez** [ManuelLoaizaVasquez/acm-icpc-team-notebook#17]
- [ ] Add README for generators
- [ ] Highlight Python syntax in LaTeX for `gen.py`
- [ ] Add math theorems and definitions as TEX files
- [ ] Add folder descriptions in README
- [ ] Move Grundy Numbers comment to LaTeX files
- [ ] Add Digits DP
- [ ] Add Chinese Remainder Theorem
- [ ] Add binomial coefficients
